# Configuration for the API Gateway in development environment
http_server:
  port: "8080"

# Addresses for backend gRPC services
services:
  auth_service_addr: "localhost:50051"
  player_profile_service_addr: "localhost:50052"

# Redis configuration for managing the matchmaking pool
redis:
  addr: "localhost:6379"
  password: ""
  db: 0

# Matchmaking specific settings (needs to match the matchmaking-service config)
matchmaking:
  pool_key: "matchmaking_pool"

kafka:
  brokers: ["localhost:9092"]
  match_found_topic: "match_found_events"
  consumer_group_id: "api_gateway_group"