# Configuration for the AuthService in development environment
grpc_server:
  port: "50051"

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "" # Use a secure password
  db_name: "auth_db"
  ssl_mode: "disable" # OK for local dev, require for prod

jwt:
  secret_key: "a_very_secret_key_for_dev" # Change this for production
  token_duration_minutes: 60

# Port for internal diagnostics (pprof, metrics)
diagnostics:
  port: "6061"