# Configuration for the MatchmakingService in the development environment
grpc_server:
  port: "50053"

redis:
  addr: "localhost:6379"
  password: "" # No password for local dev Redis
  db: 0 # Default Redis database

# Matchmaking specific settings
matchmaking:
  pool_key: "matchmaking_pool" # The key for our Redis sorted set
  check_interval_seconds: 5 # How often to check for a match
  players_per_match: 10 # For a 5v5 game

kafka:
  brokers: ["localhost:9092"]
  match_found_topic: "match_found_events"