# Configuration for the PlayerProfileService in development environment
grpc_server:
  port: "50052" # A different port from the auth-service

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: ""
  db_name: "auth_db"
  ssl_mode: "disable"

diagnostics:
  port: "6062"